const str = `https://www.app.com/pages/interactives/homesinyork2/ounty/
https://static.theledger.com/submitletter/
https://www.tcpalm.com/pages/interactives/noaa-database/
https://www.tcpalm.com/pages/interactives/restaurant-inspections/
https://www.tcpalm.com/pages/interactives/scanner/
https://www.tcpalm.com/pages/interactives/sudoku-puzzle/
https://www.tcpalm.com/pages/interactives/summer-camps-database/
https://www.tcpalm.com/pages/interactives/we-sponsor-the-treasure-coast/
https://www.thecalifornian.com/pages/interactives/tests/justice-landing/
https://www.thegleaner.com/pages/interactives/marketplace-deals/
https://www.thenews-messenger.com/pages/interactives/voter-guide/
https://www.thenews-messenger.com/pages/interactives/voter-guide/candidate-profile/
https://www.thenews-messenger.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.thenews-messenger.com/pages/interactives/voter-guide/candidates-login/
https://www.thenews-messenger.com/pages/interactives/voter-guide/candidates-preview/
https://www.thenews-messenger.com/pages/interactives/voter-guide/sample-ballot/
https://www.thenews-messenger.com/pages/interactives/voter-guide/search-results/
https://www.thenorthwestern.com/pages/interactives/preps-plus-scoreboard/
https://www.thespectrum.com/pages/interactives/best-of-the-west/
https://www.thetimesherald.com/pages/interactives/flint-water-crisis-timeline/
https://www.thetimesherald.com/pages/interactives/quiz-michigan-winters/
https://www.thetimesherald.com/pages/interactives/state-budget/
https://www.thetimesherald.com/pages/interactives/statewide-election-results/08/02/2016/
https://www.thetimesherald.com/pages/interactives/superhero-quiz/
https://www.timesrecordnews.com/pages/interactives/circulars/
https://www.timesrecordnews.com/pages/interactives/crossword/
https://www.timesrecordnews.com/pages/interactives/help/
https://www.timesrecordnews.com/pages/interactives/police-scanner/
https://www.timesrecordnews.com/pages/interactives/puzzles/
https://www.timesrecordnews.com/pages/interactives/state-high-school-standings/
https://www.timesrecordnews.com/pages/interactives/submit-anniversary/
https://www.timesrecordnews.com/pages/interactives/submit-engagement/
https://www.timesrecordnews.com/pages/interactives/submit-letter/
https://www.timesrecordnews.com/pages/interactives/submit-wedding/
https://www.timesrecordnews.com/pages/interactives/weather-cam/
https://www.vcstar.com/pages/interactives/bell-ringer-2016/
https://www.vcstar.com/pages/interactives/best-of-the-west/
https://www.vcstar.com/pages/interactives/circulars/
https://www.vcstar.com/pages/interactives/gas-prices/
https://www.vcstar.com/pages/interactives/OLD-puzzles/
https://www.vcstar.com/pages/interactives/puzzles/
https://www.vcstar.com/pages/interactives/special-sections/
https://www.vcstar.com/pages/interactives/sponsorship-ad/
https://www.vcstar.com/pages/interactives/sponsorship-request/
https://www.vcstar.com/pages/interactives/tests/justice-landing/
https://www.vcstar.com/pages/interactives/vin-scully/
https://www.visaliatimesdelta.com/pages/interactives/tests/justice-landing/
https://www.wausaudailyherald.com/pages/interactives/preps-plus-scoreboard/
https://www.wisconsinrapidstribune.com/pages/interactives/preps-plus-scoreboard/
https://www.wisfarmer.com/pages/interactives/commodities/
https://www.ydr.com/pages/interactives/homesinyork2/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/candidate-profile/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/candidates-login/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/candidates-preview/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/sample-ballot/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/search-results/`
const testStr = `
https://static.greenbaypressgazette.com/en/adchoices/
https://static.greenbaypressgazette.com/en/privacy/
https://static.greenbaypressgazette.com/en/terms/
https://static.indystar.com/en/aboutus/
https://static.indystar.com/en/adchoices/
https://static.indystar.com/en/apps/
https://static.indystar.com/en/blog-question-submission/
https://static.indystar.com/en/contact/
https://static.indystar.com/en/counter/
https://static.indystar.com/en/follow/
https://static.indystar.com/en/help/
https://static.indystar.com/en/marketing/holidaycontest/
https://static.indystar.com/en/ourcommunity/
https://static.indystar.com/en/placead/
https://static.indystar.com/en/placead/announcements/
https://static.indystar.com/en/placead/auctions/
https://static.indystar.com/en/placead/celebrations/
https://static.indystar.com/en/placead/churches/
https://static.indystar.com/en/placead/classifieds-submission/
https://static.indystar.com/en/placead/customprint/
https://static.indystar.com/en/placead/getaway-guide/
https://static.indystar.com/en/placead/jobs/
https://static.indystar.com/en/placead/legal-notices/
https://static.indystar.com/en/placead/memorials/
https://static.indystar.com/en/placead/simplifieds/
https://static.indystar.com/en/presstours/
https://static.indystar.com/en/privacy/
https://static.indystar.com/en/pulliam/pulliamapply/
https://static.indystar.com/en/rights/
https://static.indystar.com/en/rss/
https://static.indystar.com/en/submitletter/
https://static.indystar.com/en/terms/
`

const urls = str.replace(/https/g,",https").trim().split(",");

module.exports =  urls

