const urlsString = `
https://static.alamogordonews.com/advertisewithus/
https://static.alamogordonews.com/classifiedshelp/
https://static.alamogordonews.com/lettertoeditor/
https://static.alamogordonews.com/rss/
https://static.app.com/about/
https://static.app.com/advertisewithus/
https://static.app.com/asburyparkpressiheart/
https://static.app.com/classifiedshelp/
https://static.app.com/iheart/contest/
https://static.app.com/must-see/
https://static.app.com/njbestbuys/shutdown/
https://static.app.com/realestate/agents/
https://static.app.com/reportersindex/
https://static.app.com/rss/
https://static.app.com/share/
https://static.app.com/share/submit/
https://static.app.com/share/thanks/
https://static.app.com/travelmap/
https://static.argusleader.com/about/
https://static.argusleader.com/ad-order-confirmation/
https://static.argusleader.com/advertisewithus/
https://static.argusleader.com/blogs/
https://static.argusleader.com/classifiedshelp/
https://static.argusleader.com/giveaway/
https://static.argusleader.com/newsletters/
https://static.argusleader.com/rss/
https://static.argusleader.com/services_contact/
https://static.argusleader.com/siouxfallsargusleaderiheart/
https://static.argusleader.com/submitletter/
https://static.argusleader.com/travelmap/
https://static.azcentral.com/12news/inspection/
https://static.azcentral.com/about/
https://static.azcentral.com/about/12-news/
https://static.azcentral.com/about/azcentral-arizona-sports-awards/
https://static.azcentral.com/about/politicaladtracker/
https://static.azcentral.com/arizona-bus-inspection-crowd/
https://static.azcentral.com/az-war-dead/
https://static.azcentral.com/bestof/2014/how-it-works/
https://static.azcentral.com/bestof/2015/how-it-works/
https://static.azcentral.com/business/real-estate/azhousing/
https://static.azcentral.com/business/whos-next/
https://static.azcentral.com/child-safety-form/
https://static.azcentral.com/comment-form/
https://static.azcentral.com/contest-rules/
https://static.azcentral.com/contests/amazon-rewards/
https://static.azcentral.com/contests/subscription-giveaway/
https://static.azcentral.com/delete-arizona-ceo-pay-ratio/
https://static.azcentral.com/delete-arizona-restaurant-inspections/
https://static.azcentral.com/delete-arizona-school-performance/
https://static.azcentral.com/delete-arizona-top-paid-executives/
https://static.azcentral.com/dining/top-home-chef/
https://static.azcentral.com/donald-trump-tweets/
https://static.azcentral.com/e-edition/
https://static.azcentral.com/education-data/
https://static.azcentral.com/election-survey/
https://static.azcentral.com/food-for-reel/
https://static.azcentral.com/help/about/
https://static.azcentral.com/help/circulation/
https://static.azcentral.com/help/contact/
https://static.azcentral.com/help/issues/
https://static.azcentral.com/help/management/
https://static.azcentral.com/help/reprints/
https://static.azcentral.com/holiday-lights-alternate/
https://static.azcentral.com/human-cost-heat/
https://static.azcentral.com/jobs/
https://static.azcentral.com/lottery-results/
https://static.tcpalm.com/name-the-hippo-contest/
https://static.tcpalm.com/rss/
https://static.tcpalm.com/stories/behind-the-ballot/
https://static.tcpalm.com/stories/life-before-death/
https://static.tcpalm.com/submit-forms/
https://static.tcpalm.com/submit-your-pictures/
https://static.tcpalm.com/traffic/
https://static.tcpalm.com/webcams/
https://static.tennessean.com/about/
https://static.tennessean.com/classifiedshelp/
https://static.tennessean.com/crossword/
https://static.tennessean.com/faq/
https://static.tennessean.com/letter-editor/
https://static.tennessean.com/realestate/agents/
https://static.tennessean.com/reportersindex/
https://static.tennessean.com/rss/
https://static.tennessean.com/thanks/
https://static.tennessean.com/travelmap/
https://static.theadvertiser.com/20under40/
https://static.theadvertiser.com/about/
https://static.theadvertiser.com/advertise/
https://static.theadvertiser.com/athleteoftheweek/
https://static.theadvertiser.com/classifiedshelp/
https://static.theadvertiser.com/coaches-poll/
https://static.theadvertiser.com/disaster-recovery-guide/
https://static.theadvertiser.com/get-this/
https://static.theadvertiser.com/lafayette-civic-cup-award-nomination/
https://static.theadvertiser.com/lafayettelatheadvertiseriheart/
https://static.theadvertiser.com/publications/
https://static.theadvertiser.com/quikquarterhelp/
https://static.theadvertiser.com/rss/
https://static.theadvertiser.com/submitletter/
https://static.theadvertiser.com/teacherwishlists/
https://static.theadvertiser.com/thanks/
https://static.theadvertiser.com/timesofacadiana/about/
https://static.theadvertiser.com/timesofacadiana/faq/
https://static.theadvertiser.com/travelmap/
https://static.theadvertiser.com/yes/
https://static.thecalifornian.com/about/
https://static.thecalifornian.com/advertise/
https://static.thecalifornian.com/classifiedshelp/
https://static.thecalifornian.com/lettertoeditor/
https://static.thecalifornian.com/rss/
https://static.thecalifornian.com/salinas-homicides-2016/
https://static.thecalifornian.com/salinascalifornianiheart/
https://static.thecalifornian.com/submissions/
https://static.thedailyjournal.com/about/
https://static.thedailyjournal.com/anniversaryannouncements/
https://static.thedailyjournal.com/birthannouncements/
https://static.thedailyjournal.com/classifiedshelp/
https://static.thedailyjournal.com/engagementannouncements/
https://static.thedailyjournal.com/localhistory/
https://static.thedailyjournal.com/reportersindex/
https://static.thedailyjournal.com/rss/
https://static.thedailyjournal.com/vinelanddailyjournaliheart/
https://static.thedailyjournal.com/weddingannouncements/
https://static.thegleaner.com/about/
https://static.thegleaner.com/classifiedshelp/
https://static.thegleaner.com/rss/
https://static.thehammontonnews.com/about/
https://static.thehammontonnews.com/advertise/
https://static.thehammontonnews.com/rss/
https://static.theleafchronicle.com/aboutus/
https://static.theleafchronicle.com/clarksvillethleafchronicleiheart/
https://static.theleafchronicle.com/classifiedshelp/
https://static.theleafchronicle.com/datacentral/
https://static.theleafchronicle.com/ethicalconduct/
https://static.theleafchronicle.com/realestate/agents/
https://static.theleafchronicle.com/rss/
https://static.theleafchronicle.com/santaletters/
https://static.theleafchronicle.com/share/submit/
https://static.theleafchronicle.com/submitletter/
https://static.theleafchronicle.com/thanks/
https://static.theledger.com/submitletter/
https://static.thenews-messenger.com/announcements/
https://static.thenews-messenger.com/back-issues/
https://static.thenews-messenger.com/classifiedshelp/
https://static.thenews-messenger.com/fremontthenewsmessengeriheart/
https://static.thenews-messenger.com/rss/
https://static.thenews-messenger.com/thank-you/
https://static.thenewsstar.com/aboutus/
https://static.thenewsstar.com/advertise/
https://static.thenewsstar.com/advertising-staff/
https://static.thenewsstar.com/advertisinginquiries/
https://static.thenewsstar.com/classifiedshelp/
https://static.thenewsstar.com/contactusform/
https://static.thenewsstar.com/games/
https://static.thenewsstar.com/goodfellows/
https://static.thenewsstar.com/monroethenewsstariheart/
https://static.thenewsstar.com/opinion-submissions/
https://static.thenewsstar.com/rss/
https://static.thenewsstar.com/stocks/
https://static.thenewsstar.com/submitaletter/
https://static.thenewsstar.com/thanks/
https://static.thenorthwestern.com/bowling-scores/
https://static.thenorthwestern.com/classifiedshelp/
https://static.thenorthwestern.com/commitment/
https://static.thenorthwestern.com/reportersindex_removed/
https://static.thenorthwestern.com/rss/
https://static.thenorthwestern.com/submit-letter/
https://static.thespectrum.com/about/
https://static.thespectrum.com/classifiedshelp/
https://static.thespectrum.com/comics/
https://static.thespectrum.com/FAMILY0402/
https://static.thespectrum.com/FAMILY0403/
https://static.thespectrum.com/follow/
https://static.thespectrum.com/games/
https://static.thespectrum.com/horoscopes/
https://static.thespectrum.com/lettertoeditor/
https://static.thespectrum.com/magazine/
https://static.thespectrum.com/puzzles/
https://static.thespectrum.com/realestate/agents/
https://static.thespectrum.com/rss/
https://static.thespectrum.com/saintgeorgespectrumiheart/
https://static.thespectrum.com/submitamissionary/
https://static.thespectrum.com/thanks/
https://static.thespectrum.com/vote/
https://static.thestarpress.com/about/
https://static.thestarpress.com/babyoftheyear/
https://static.thestarpress.com/babyoftheyear/voting/
https://static.thestarpress.com/classifiedshelp/
https://static.thestarpress.com/contactus-ads/
https://static.thestarpress.com/contactus-newsroom/
https://static.thestarpress.com/finest/
https://static.thestarpress.com/healthsource/
https://static.thestarpress.com/munciethestarpressiheart/
https://static.thestarpress.com/poy/
https://static.thestarpress.com/rss/
https://static.thetimesherald.com/aboutus/
https://static.thetimesherald.com/classifiedshelp/
https://static.thetimesherald.com/ethicalconduct/
https://static.thetimesherald.com/facebookfaq/
https://static.thetimesherald.com/faq/
https://static.thetimesherald.com/lettertoeditor/
https://static.thetimesherald.com/porthurontimesheraldiheart/
https://static.thetimesherald.com/realestate/agents/
https://static.thetimesherald.com/rss/
https://static.thetimesherald.com/rules/
https://static.thetimesherald.com/tasteofhome/
https://static.thetowntalk.com/aboutus/
https://static.thetowntalk.com/advertise/
https://static.thetowntalk.com/alexandriaiheartcountry/
https://static.thetowntalk.com/classifiedshelp/
https://static.thetowntalk.com/faq/
https://static.thetowntalk.com/rss/
https://static.thetowntalk.com/submitaletter/
https://static.thetowntalk.com/thanks/
https://static.timesrecordnews.com/20under40/
https://static.timesrecordnews.com/classifiedshelp/
https://static.timesrecordnews.com/games/
https://static.timesrecordnews.com/rss/
https://static.timesrecordnews.com/star-student/
https://static.upstateparent.com/about/
https://static.upstateparent.com/upstate-parent-feedback/
https://static.usatoday.com/about-usaweekend/
https://static.usatoday.com/about/
https://static.usatoday.com/about/awards/
https://static.usatoday.com/about/brand/
https://static.usatoday.com/about/green/
https://static.usatoday.com/about/logos/
https://static.usatoday.com/about/politicaladtracker/
https://static.usatoday.com/about/timeline/
https://static.usatoday.com/Author_chat/
https://static.usatoday.com/carnival-cruise-sweepstakes-rules/
https://static.usatoday.com/do-not-use/sports/odds/
https://static.usatoday.com/editorial-policy-deleted/
https://static.usatoday.com/embark/
https://static.usatoday.com/embark/faqs/
https://static.usatoday.com/factchecking/
https://static.usatoday.com/grand-canyon-sweepstakes/
https://static.usatoday.com/home/a/
https://static.usatoday.com/home/b/
https://static.usatoday.com/interactives/elections-forecast-2014/
https://static.usatoday.com/mobile-apps/
https://static.usatoday.com/mobiletest/
https://static.usatoday.com/model-legislation-ingestion/
https://static.usatoday.com/motley-fool/
https://static.usatoday.com/policing/submit/
https://static.usatoday.com/policing/thanks/
https://static.usatoday.com/reporters/opinion-columnists/
https://static.usatoday.com/rss/
https://static.usatoday.com/shop/
https://static.usatoday.com/submission-guidelines/
https://static.usatoday.com/submitcolumn/
https://static.usatoday.com/submitletter/
https://static.usatoday.com/unsupported-browser/
https://static.usatoday.com/usat-static-mobile/
https://static.usatoday.com/usatlifeiheart/
https://static.usatoday.com/usatoday-standard-subscription/
https://static.usatoday.com/video/contest/
https://static.usatoday.com/VRstories/
https://static.usatoday.com/wine-your-way-sweepstakes-rules/
https://static.vcstar.com/beachcam/
https://static.vcstar.com/classifiedshelp/
https://static.vcstar.com/community-relations/
https://static.vcstar.com/contractors/
https://static.vcstar.com/horoscopes/
https://static.vcstar.com/rainfall-totals/
https://static.vcstar.com/rss/
https://static.vcstar.com/sponsorships-do-not-use/
https://static.vcstar.com/submit-letter/
https://static.vcstar.com/subscriber-message/
https://static.vcstar.com/sweepstakes/
https://static.vcstar.com/vin-scully/
https://static.vcstar.com/where-to-write/
https://static.visaliatimesdelta.com/about/
https://static.visaliatimesdelta.com/advertisewithus/
https://static.visaliatimesdelta.com/classifiedshelp/
https://static.visaliatimesdelta.com/connectII/
https://static.visaliatimesdelta.com/contestrules/
https://static.visaliatimesdelta.com/lettertoeditor/
https://static.visaliatimesdelta.com/realestate/
https://static.visaliatimesdelta.com/realestate/agents/
https://static.visaliatimesdelta.com/rss/
https://static.visaliatimesdelta.com/sharephotosvideos/
https://static.visaliatimesdelta.com/sharepressrelease/
https://static.visaliatimesdelta.com/visaliatularetimesdeltaiheart/
https://static.wausaudailyherald.com/classifiedshelp/
https://static.wausaudailyherald.com/commitment/
https://static.wausaudailyherald.com/reportersindex_removed/
https://static.wausaudailyherald.com/rss/
https://static.wausaudailyherald.com/submit-letter/
https://static.wisconsinrapidstribune.com/classifiedshelp/
https://static.wisconsinrapidstribune.com/commitment/
https://static.wisconsinrapidstribune.com/reportersindex_removed/
https://static.wisconsinrapidstribune.com/rss/
https://static.wisconsinrapidstribune.com/submit-letter/
https://static.wisfarmer.com/about-us/
https://static.wisfarmer.com/classifiedshelp/
https://static.wisfarmer.com/connect-with-us/
https://static.wisfarmer.com/rss/
https://static.wisfarmer.com/subscribe/
https://static.ydr.com/about/
https://static.ydr.com/apps-test/
https://static.ydr.com/contactus-delete/
https://static.ydr.com/contactus-test/
https://static.ydr.com/homesinyork/
https://static.ydr.com/rss/
https://static.ydr.com/submitletter/
https://static.ydr.com/subscription/
https://static.yorkdispatch.com/about/
https://static.yorkdispatch.com/archive/
https://static.yorkdispatch.com/rss/
https://static.yorkdispatch.com/submitletter/
https://static.zanesvilletimesrecorder.com/back-issues/
https://static.zanesvilletimesrecorder.com/classifiedshelp/
https://static.zanesvilletimesrecorder.com/realestate/agents/
https://static.zanesvilletimesrecorder.com/rss/
https://static.zanesvilletimesrecorder.com/thank-you/
https://static.zanesvilletimesrecorder.com/zanesvilletimesrecorderiheart/
`
const urlsStringTwo = `
https://www.app.com/pages/interactives/homesinyork2/
https://www.argusleader.com/pages/interactives/food-falls-bracket-challenge/
https://www.argusleader.com/pages/interactives/food-falls-bracket-challenge1/
https://www.argusleader.com/pages/interactives/news/approved-and-denied-license-plates/
https://www.argusleader.com/pages/interactives/restaurant-brackets/
https://www.azcentral.com/pages/interactives/100-ways-to-survive-summer/
https://www.azcentral.com/pages/interactives/2016_summer_olympics_rio/
https://www.azcentral.com/pages/interactives/arizona-data/salary-database-concern-form/
https://www.azcentral.com/pages/interactives/arizona-data/salary-individual/
https://www.azcentral.com/pages/interactives/arizona-four-corners/
https://www.azcentral.com/pages/interactives/arizona-monsoon-payson-flash-flood-deaths/
https://www.azcentral.com/pages/interactives/arizona-parole-myth/
https://www.azcentral.com/pages/interactives/arizona-rio-olympics-2016/
https://www.azcentral.com/pages/interactives/arizona-school-bus-inspections-data/
https://www.azcentral.com/pages/interactives/arizona-school-bus-inspections/
https://www.azcentral.com/pages/interactives/arizona-travel-guide/
https://www.azcentral.com/pages/interactives/best-arizona-guide/
https://www.azcentral.com/pages/interactives/best-of-the-west/
https://www.azcentral.com/pages/interactives/childwelfare/
https://www.azcentral.com/pages/interactives/comics/
https://www.azcentral.com/pages/interactives/foodwaste/
https://www.azcentral.com/pages/interactives/full-page-js-demo/
https://www.azcentral.com/pages/interactives/full-page-js-demo2/
https://www.azcentral.com/pages/interactives/john-mccain-biography/
https://www.azcentral.com/pages/interactives/jovanna-calzadillas-las-vegas-shooting/
https://www.azcentral.com/pages/interactives/list-phoenix-restaurants-near-me/
https://www.azcentral.com/pages/interactives/local/arizona/best-reads/avondale-quads/
https://www.azcentral.com/pages/interactives/mafia-in-our-midst/
https://www.azcentral.com/pages/interactives/map-phoenix-restaurants-near-me/
https://www.azcentral.com/pages/interactives/national-park-service-centennial/
https://www.azcentral.com/pages/interactives/navajo-housing/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/arizona-government-salary-database/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/arizona-police-shootings/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/arizona-republic-100-largest-companies-hiring-in-phoenix-arizona/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/arizona-schools-measles-vaccinations-rates/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/arizona-university-salaries-asu-ua-nau/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/best-rated-arizona-hospitals-star-ratings/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/cactus-league-spring-training-attendance-schedules/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/dcs-home-visit-parent-education-services/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/dolphin-deaths-united-states-dolphinaris-arizona/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/full-pool-inspection-database/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/full-restaurant-inspection-database/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/highest-paid-CEO-salary/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/highest-paying-jobs-employees/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/how-many-students-use-school-vouchers-esa-empowerment-scholarship-accounts/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/most-college-graduates-highest-completion-rates-Arizona-high-schools/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/phoenix-area-maricopa-county-homicides-murders/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/phoenix-area-pool-safety-inspections/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/phoenix-area-tucson-city-salaries/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/phoenix-home-values-street-scout/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/restaurants/maricopa-county-health-department-inspections/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/school-letter-grades-2019/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/school-ratings-letter-grades/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/stock-values-largest-companies-arizona/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/teacher-allegations-sexual-misconduct/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/where-arizona-pedestrians-hit-car-crash-death/
https://www.azcentral.com/pages/interactives/news/politics/nation/model-legislation/
https://www.azcentral.com/pages/interactives/phoenix-area-food-hubs/
https://www.azcentral.com/pages/interactives/phoenix-holiday-lights-map/
https://www.azcentral.com/pages/interactives/running-wild-horse-management/
https://www.azcentral.com/pages/interactives/snap-story-demo/
https://www.azcentral.com/pages/interactives/tuesday-trivia/
https://www.azcentral.com/pages/interactives/wild-horse-management-mustangs-north-america/
https://www.azcentral.com/pages/interactives/women-suffrage-timeline/
https://www.battlecreekenquirer.com/pages/interactives/11/2016/calhoun-county-election-results/
https://www.battlecreekenquirer.com/pages/interactives/2017-Calhoun-County-election-results/
https://www.battlecreekenquirer.com/pages/interactives/calhoun-election-results/08/2016/
https://www.battlecreekenquirer.com/pages/interactives/endangered-species-quiz/
https://www.battlecreekenquirer.com/pages/interactives/flint-water-crisis-timeline/
https://www.battlecreekenquirer.com/pages/interactives/michigan-castles-tour/
https://www.battlecreekenquirer.com/pages/interactives/michigan-musicians-quiz/
https://www.battlecreekenquirer.com/pages/interactives/quiz-michigan-winters/
https://www.battlecreekenquirer.com/pages/interactives/quiz/invasives/
https://www.battlecreekenquirer.com/pages/interactives/state-budget/
https://www.battlecreekenquirer.com/pages/interactives/statewide-election-results/08/02/2016/
https://www.battlecreekenquirer.com/pages/interactives/superhero-quiz/
https://www.bucyrustelegraphforum.com/pages/interactives/voter-guide/
https://www.bucyrustelegraphforum.com/pages/interactives/voter-guide/candidate-profile/
https://www.bucyrustelegraphforum.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.bucyrustelegraphforum.com/pages/interactives/voter-guide/candidates-login/
https://www.bucyrustelegraphforum.com/pages/interactives/voter-guide/candidates-preview/
https://www.bucyrustelegraphforum.com/pages/interactives/voter-guide/sample-ballot/
https://www.bucyrustelegraphforum.com/pages/interactives/voter-guide/search-results/
https://www.burlingtonfreepress.com/pages/interactives/ski-dev-26/
https://www.caller.com/pages/interactives/archive-faq/
https://www.caller.com/pages/interactives/archive-help/
https://www.caller.com/pages/interactives/archive-pricing/
https://www.caller.com/pages/interactives/archives/
https://www.caller.com/pages/interactives/circulars-old/
https://www.caller.com/pages/interactives/classifieds/
https://www.caller.com/pages/interactives/comics/
https://www.caller.com/pages/interactives/contact-form/
https://www.caller.com/pages/interactives/crime/
https://www.caller.com/pages/interactives/food-and-recipes/
https://www.caller.com/pages/interactives/garden-tips/
https://www.caller.com/pages/interactives/selena-quiz/
https://www.caller.com/pages/interactives/selena-social-wall/
https://www.caller.com/pages/interactives/selena-timeline/
https://www.caller.com/pages/interactives/sponsorship-form/
https://www.caller.com/pages/interactives/vivacc-social-wall/
https://www.chillicothegazette.com/pages/interactives/voter-guide/
https://www.chillicothegazette.com/pages/interactives/voter-guide/candidate-profile/
https://www.chillicothegazette.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.chillicothegazette.com/pages/interactives/voter-guide/candidates-login/
https://www.chillicothegazette.com/pages/interactives/voter-guide/candidates-preview/
https://www.chillicothegazette.com/pages/interactives/voter-guide/sample-ballot/
https://www.chillicothegazette.com/pages/interactives/voter-guide/search-results/
https://www.cincinnati.com/pages/interactives/elections/ohio-early-voting-absentee-ballot/
https://www.cincinnati.com/pages/interactives/homelesscamps/
https://www.cincinnati.com/pages/interactives/kentucky/primary/2018/
https://www.cincinnati.com/pages/interactives/news/politics/elections/ohioresults/
https://www.cincinnati.com/pages/interactives/oh12electionresults/
https://www.cincinnati.com/pages/interactives/reds360-devplayer/
https://www.cincinnati.com/pages/interactives/reds360/
https://www.cincinnati.com/pages/interactives/share/submissions/
https://www.cincinnati.com/pages/interactives/sports/2019collegefootballpickoff/
https://www.clarionledger.com/pages/interactives/GBLD/
https://www.clarionledger.com/pages/interactives/GBLD/rules/
https://www.clarionledger.com/pages/interactives/GBLD/thank-you/
https://www.clarionledger.com/pages/interactives/gone-dev/
https://www.coloradoan.com/pages/interactives/andrew-vanderwal-investigation-child-sexual-abuse-prey-pursuit/
https://www.coloradoan.com/pages/interactives/best-of-the-west/
https://www.coloradoan.com/pages/interactives/dev-race-the-pro/
https://www.coloradoan.com/pages/interactives/usa-pro-biking-challenge/
https://www.commercialappeal.com/pages/interactives/archives/
https://www.commercialappeal.com/pages/interactives/circulars/
https://www.commercialappeal.com/pages/interactives/comics/
https://www.commercialappeal.com/pages/interactives/games/
https://www.commercialappeal.com/pages/interactives/horoscopes/
https://www.commercialappeal.com/pages/interactives/sportsdirectinc-mobile/
https://www.coshoctontribune.com/pages/interactives/voter-guide/
https://www.coshoctontribune.com/pages/interactives/voter-guide/candidate-profile/
https://www.coshoctontribune.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.coshoctontribune.com/pages/interactives/voter-guide/candidates-login/
https://www.coshoctontribune.com/pages/interactives/voter-guide/candidates-preview/
https://www.coshoctontribune.com/pages/interactives/voter-guide/sample-ballot/
https://www.coshoctontribune.com/pages/interactives/voter-guide/search-results/
https://www.courier-journal.com/pages/interactives/austin-rising/
https://www.courier-journal.com/pages/interactives/derby360/
https://www.courier-journal.com/pages/interactives/healing-austin/
https://www.courier-journal.com/pages/interactives/louisville/aroundthebluegrass/
https://www.courier-journal.com/pages/interactives/louisville/seeclickfix/
https://www.courier-journal.com/pages/interactives/staff-directory/
https://www.courierpress.com/pages/interactives/archives/
https://www.courierpress.com/pages/interactives/circulars/
https://www.courierpress.com/pages/interactives/isp-meth-map/
https://www.courierpress.com/pages/interactives/marketplace-deals/
https://www.courierpress.com/pages/interactives/podcasts/
https://www.courierpress.com/pages/interactives/scanner/
https://www.courierpress.com/pages/interactives/sudoku/
https://www.courierpress.com/pages/interactives/warrick-county-election-center/
https://www.daily-times.com/pages/interactives/best-of-the-west/
https://www.democratandchronicle.com/pages/interactives/elections-forecast-2014-133/
https://www.democratandchronicle.com/pages/interactives/elections-forecast-2014-a75/
https://www.democratandchronicle.com/pages/interactives/require/
https://www.desertsun.com/pages/interactives/best-of-the-west/
https://www.desertsun.com/pages/interactives/desertsun/2016/11/08/election-results/
https://www.desertsun.com/pages/interactives/metrics/
https://www.desertsun.com/pages/interactives/metrics/dashboard/
https://www.desertsun.com/pages/interactives/metrics/pressbox/
https://www.desmoinesregister.com/pages/interactives/alt-story-telling-template/
https://www.desmoinesregister.com/pages/interactives/brian-powers-nppa-win/
https://www.desmoinesregister.com/pages/interactives/dev-iowa-political-soapbox/
https://www.desmoinesregister.com/pages/interactives/harvest-dev/
https://www.desmoinesregister.com/pages/interactives/harvest-of-change-dev/
https://www.desmoinesregister.com/pages/interactives/harvest-of-change-nomination/
https://www.desmoinesregister.com/pages/interactives/iowa-primary-2018-hubbell-reynolds-axne-finkenauer-women-voting-democrats-republicans-convention/
https://www.desmoinesregister.com/pages/interactives/iowa-state-fair-political-soapbox/
https://www.desmoinesregister.com/pages/interactives/news/interactive-homicide-map/
https://www.desmoinesregister.com/pages/interactives/speed-camera-des-moines-tickets-cost-I-235-crashes-wrecks/
https://www.desmoinesregister.com/pages/interactives/unity-test/
https://www.detroitnews.com/pages/interactives/winterfest/
https://www.elpasotimes.com/pages/interactives/best-of-the-west/
https://www.elpasotimes.com/pages/interactives/sports/2016-football-preview/
https://www.eveningsun.com/pages/interactives/eveningsun/specialsections/
https://www.fdlreporter.com/pages/interactives/preps-plus-scoreboard/
https://www.floridatoday.com/pages/interactives/brandyhallmap/
https://www.floridatoday.com/pages/interactives/haunted-brevard-titusville-playhouse/
https://www.freep.com/pages/interactives/1967-detroit-riot/
https://www.freep.com/pages/interactives/2015-michigan-election-results//2015-michigan-primary-election/
https://www.freep.com/pages/interactives/2015autoshow/
https://www.freep.com/pages/interactives/2017-mstep-sat-michigan-results/
https://www.freep.com/pages/interactives/2018-mstep-sat-michigan-results/
https://www.freep.com/pages/interactives/2019-mstep-sat-michigan-results123456789/
https://www.freep.com/pages/interactives/32-players-bracket/
https://www.freep.com/pages/interactives/50-detroiters/
https://www.freep.com/pages/interactives/all-aboard-the-qline/
https://www.freep.com/pages/interactives/baseballtest18/
https://www.freep.com/pages/interactives/boblo-boat-3d-virtual-tour-columbia/
https://www.freep.com/pages/interactives/bracketfake5/
https://www.freep.com/pages/interactives/civics-test/
https://www.freep.com/pages/interactives/colemanyoung100/
https://www.freep.com/pages/interactives/commcollegeexpenditures/
https://www.freep.com/pages/interactives/commcollegegradrates/
https://www.freep.com/pages/interactives/commcollegeprezpay/
https://www.freep.com/pages/interactives/communitycollegerevenue/
https://www.freep.com/pages/interactives/contest/salwan-georges/
https://www.freep.com/pages/interactives/Detroit_Lions_NFL_draft_database/
https://www.freep.com/pages/interactives/detroit-50-greatest-songs/
https://www.freep.com/pages/interactives/detroit-free-press-apprenticeship-application/
https://www.freep.com/pages/interactives/detroit-greatest-songs/
https://www.freep.com/pages/interactives/detroit-greatest-songs/ballot/
https://www.freep.com/pages/interactives/detroit-greatest-songs/complete-list/
https://www.freep.com/pages/interactives/detroit-greatest-songs/faq/
https://www.freep.com/pages/interactives/detroit-library-burton-historical-collection/
https://www.freep.com/pages/interactives/detroit-lions-nfl-draft-table/
https://www.freep.com/pages/interactives/detroit-scoreboard/
https://www.freep.com/pages/interactives/detroit-street-art/
https://www.freep.com/pages/interactives/detroit-then-and-now/
https://www.freep.com/pages/interactives/detroit-tigers-history/
https://www.freep.com/pages/interactives/detroitschoolboard/
https://www.freep.com/pages/interactives/disorderly-conduct/
https://www.freep.com/pages/interactives/drinking-water/
https://www.freep.com/pages/interactives/driving-detroit-fake-file/109/
https://www.freep.com/pages/interactives/election-results-may-2018/
https://www.freep.com/pages/interactives/endangered-species-quiz/
https://www.freep.com/pages/interactives/flint-water-crisis-timeline/
https://www.freep.com/pages/interactives/flint-water-crisis/a-visual-essay/
https://www.freep.com/pages/interactives/flint-water-crisis/a-visual-essay/a_community_responds/
https://www.freep.com/pages/interactives/flint-water-crisis/a-visual-essay/all_eyes_on_flint/
https://www.freep.com/pages/interactives/flint-water-crisis/a-visual-essay/living_with_lead/
https://www.freep.com/pages/interactives/flint-water-crisis/a-visual-essay/the_trek_for_water/
https://www.freep.com/pages/interactives/flint-water-crisis/a-visual-essay/unheeded_warnings/
https://www.freep.com/pages/interactives/footballsacks/
https://www.freep.com/pages/interactives/freep-default-template/
https://www.freep.com/pages/interactives/freep-special-template-v2/
https://www.freep.com/pages/interactives/freep-special-template/
https://www.freep.com/pages/interactives/freep/election-results/2016/05/03/
https://www.freep.com/pages/interactives/freep/election-results/general/2016/keyprecincts/
https://www.freep.com/pages/interactives/freep/election-results/general/2016/macomb/
https://www.freep.com/pages/interactives/freep/election-results/general/2016/oakland/
https://www.freep.com/pages/interactives/freep/election-results/general/2016/wayne/
https://www.freep.com/pages/interactives/freep/election-results/general/2017/macomb/
https://www.freep.com/pages/interactives/freep/election-results/general/2017/oakland/
https://www.freep.com/pages/interactives/freep/election-results/general/2017/wayne/
https://www.freep.com/pages/interactives/freep/election-results/primary/2016/macomb/
https://www.freep.com/pages/interactives/freep/election-results/primary/2016/oakland/
https://www.freep.com/pages/interactives/freep/election-results/primary/2016/wayne/
https://www.freep.com/pages/interactives/freep/election-results/primary/2017/macomb/
https://www.freep.com/pages/interactives/freep/election-results/primary/2017/oakland/
https://www.freep.com/pages/interactives/freep/election-results/primary/2017/wayne/
https://www.freep.com/pages/interactives/freep/election-results/primary/2018/congress/
https://www.freep.com/pages/interactives/freep/election-results/primary/2018/macomb/
https://www.freep.com/pages/interactives/freep/election-results/primary/2018/oakland/
https://www.freep.com/pages/interactives/freep/election-results/primary/2018/state/
https://www.freep.com/pages/interactives/freep/election-results/primary/2018/wayne/
https://www.freep.com/pages/interactives/freep/election/voter-guide/august-2017/
https://www.freep.com/pages/interactives/freep/election/voter-guide/november-2017/
https://www.freep.com/pages/interactives/freep/test26/
https://www.freep.com/pages/interactives/freep/top-workplaces-2017/
https://www.freep.com/pages/interactives/freep/top-workplaces-2018/
https://www.freep.com/pages/interactives/homeflipper24/
https://www.freep.com/pages/interactives/infinitywarfake/
https://www.freep.com/pages/interactives/lbtester/file/
https://www.freep.com/pages/interactives/lions_draft8/
https://www.freep.com/pages/interactives/little-caesars-arena/team-steel/
https://www.freep.com/pages/interactives/little-flower-shrine-basilica-3D-tour/
https://www.freep.com/pages/interactives/macomb-county-michigan-election-results/
https://www.freep.com/pages/interactives/manuelmorountimeline/
https://www.freep.com/pages/interactives/mike-thompson-elections-2016-cartoons/
https://www.freep.com/pages/interactives/mike-thompson-gerrymandering/
https://www.freep.com/pages/interactives/new/test/driving/
https://www.freep.com/pages/interactives/oakland-county-michigan-election-results/
https://www.freep.com/pages/interactives/obama-speech-flint-water-crisis/
https://www.freep.com/pages/interactives/oscarderby/
https://www.freep.com/pages/interactives/oscarderby2016/
https://www.freep.com/pages/interactives/parkinglots-fake-file/
https://www.freep.com/pages/interactives/police-chases-deadlier-for-blacks/
https://www.freep.com/pages/interactives/quiz-michigan-winters/
https://www.freep.com/pages/interactives/restaurant-of-the-year/readers-choice/
https://www.freep.com/pages/interactives/sos-2015/
https://www.freep.com/pages/interactives/speculatorsdetroit123/
https://www.freep.com/pages/interactives/squatterstest8/
https://www.freep.com/pages/interactives/state-budget/
https://www.freep.com/pages/interactives/state-house-michigan-election-results/
https://www.freep.com/pages/interactives/summer-movie-showdown/
https://www.freep.com/pages/interactives/test/sp/2018/
https://www.freep.com/pages/interactives/tester/endowment/test1/
https://www.freep.com/pages/interactives/testing-360s/
https://www.freep.com/pages/interactives/tigersnorris119/
https://www.freep.com/pages/interactives/tweetus/
https://www.freep.com/pages/interactives/umendowments-tester-not-real9/
https://www.freep.com/pages/interactives/umichendowment/
https://www.freep.com/pages/interactives/vintage-detroit-signs/
https://www.freep.com/pages/interactives/wayne-county-michigan-election-results/
https://www.freep.com/pages/interactives/wstesthistory/
https://www.freep.com/pages/interactives/youthservices/
https://www.gosanangelo.com/pages/interactives/20-under-40/
https://www.gosanangelo.com/pages/interactives/away-in-a-manger/
https://www.gosanangelo.com/pages/interactives/circulars/
https://www.gosanangelo.com/pages/interactives/comics/
https://www.gosanangelo.com/pages/interactives/deck-the-halls/
https://www.gosanangelo.com/pages/interactives/games/
https://www.gosanangelo.com/pages/interactives/gas-prices/
https://www.gosanangelo.com/pages/interactives/hark-the-herald-angels-sing/
https://www.gosanangelo.com/pages/interactives/here-we-come-a-wassailing/
https://www.gosanangelo.com/pages/interactives/holiday-songbook/
https://www.gosanangelo.com/pages/interactives/it-came-upon-a-midnight-clear/
https://www.gosanangelo.com/pages/interactives/jingle-bells/
https://www.gosanangelo.com/pages/interactives/little-town-of-bethlehem/
https://www.gosanangelo.com/pages/interactives/o-christmas-tree/
https://www.gosanangelo.com/pages/interactives/o-come-all-ye-faithful/
https://www.gosanangelo.com/pages/interactives/o-holy-night/
https://www.gosanangelo.com/pages/interactives/old_classifieds/
https://www.gosanangelo.com/pages/interactives/outstanding-arrest-warrants/
https://www.gosanangelo.com/pages/interactives/silent-night/
https://www.gosanangelo.com/pages/interactives/submit-letter/
https://www.gosanangelo.com/pages/interactives/we-wish-you-a-merry-christmas/
https://www.gosanangelo.com/pages/interactives/what-child-is-this/
https://www.greatfallstribune.com/pages/interactives/best-of-the-west/
https://www.greenbaypressgazette.com/pages/interactives/preps-plus-scoreboard/
https://www.hometownlife.com/pages/interactives/flint-water-crisis-timeline/
https://www.htrnews.com/pages/interactives/preps-plus-scoreboard/
https://www.independentmail.com/pages/interactives/circulars/
https://www.indystar.com/pages/interactives/2019/indy-500-events/
https://www.indystar.com/pages/interactives/iheart/contest/
https://www.jsonline.com/pages/interactives/2016-green-bay-packers-schedule/
https://www.jsonline.com/pages/interactives/august-2016-milwaukee-primary-election-results/
https://www.jsonline.com/pages/interactives/august-2016-wisconsin-primary-election-results/
https://www.jsonline.com/pages/interactives/brewers-home-run-database/
https://www.jsonline.com/pages/interactives/classified-retired/
https://www.jsonline.com/pages/interactives/comics/
https://www.jsonline.com/pages/interactives/crime-map/
https://www.jsonline.com/pages/interactives/event-listings/
https://www.jsonline.com/pages/interactives/events-calendar/
https://www.jsonline.com/pages/interactives/games/
https://www.jsonline.com/pages/interactives/horoscopes/
https://www.jsonline.com/pages/interactives/Land--Space-Development-Database/
https://www.jsonline.com/pages/interactives/milwaukee-tv-listings/
https://www.jsonline.com/pages/interactives/mjs-newsroom-staff/
https://www.jsonline.com/pages/interactives/packers-bars/
https://www.jsonline.com/pages/interactives/preps-plus-scoreboard/
https://www.jsonline.com/pages/interactives/rebuilding-the-milwaukee-brewers/
https://www.jsonline.com/pages/interactives/seven-days-of-holiday-savings/
https://www.kitsapsun.com/pages/interactives/comics/
https://www.kitsapsun.com/pages/interactives/help/
https://www.kitsapsun.com/pages/interactives/kpbj-april-2016-edition/
https://www.kitsapsun.com/pages/interactives/kpbj-august-2016-edition/
https://www.kitsapsun.com/pages/interactives/kpbj-february-2016-edition/
https://www.kitsapsun.com/pages/interactives/kpbj-january-2016-edition/
https://www.kitsapsun.com/pages/interactives/kpbj-july-2016-edition/
https://www.kitsapsun.com/pages/interactives/kpbj-june-2016-edition/
https://www.kitsapsun.com/pages/interactives/kpbj-march-2016-edition/
https://www.kitsapsun.com/pages/interactives/kpbj-may-2016-edition/
https://www.kitsapsun.com/pages/interactives/kpbj-november-2016-edition/
https://www.kitsapsun.com/pages/interactives/kpbj-september-2016-edition/
https://www.kitsapsun.com/pages/interactives/puzzles/
https://www.kitsapsun.com/pages/interactives/sales-inquiries/
https://www.kitsapsun.com/pages/interactives/submit-announcement/
https://www.kitsapsun.com/pages/interactives/submit-newstip/
https://www.knoxnews.com/pages/interactives/archives/
https://www.knoxnews.com/pages/interactives/bids-proposals/
https://www.knoxnews.com/pages/interactives/circulars/
https://www.knoxnews.com/pages/interactives/classifieds/
https://www.knoxnews.com/pages/interactives/crossword/
https://www.knoxnews.com/pages/interactives/delete-gorilla-cam/
https://www.knoxnews.com/pages/interactives/foreclosures/
https://www.knoxnews.com/pages/interactives/hearings/
https://www.knoxnews.com/pages/interactives/horoscopes/
https://www.knoxnews.com/pages/interactives/legal-ads/
https://www.knoxnews.com/pages/interactives/legals/
https://www.knoxnews.com/pages/interactives/lowest-gas-prices-in-knoxville/
https://www.knoxnews.com/pages/interactives/market-square-cam/
https://www.knoxnews.com/pages/interactives/public-notices/
https://www.knoxnews.com/pages/interactives/public-sales/
https://www.knoxnews.com/pages/interactives/sudoku-puzzle/
https://www.lancastereaglegazette.com/pages/interactives/voter-guide/
https://www.lancastereaglegazette.com/pages/interactives/voter-guide/candidate-profile/
https://www.lancastereaglegazette.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.lancastereaglegazette.com/pages/interactives/voter-guide/candidates-login/
https://www.lancastereaglegazette.com/pages/interactives/voter-guide/candidates-preview/
https://www.lancastereaglegazette.com/pages/interactives/voter-guide/sample-ballot/
https://www.lancastereaglegazette.com/pages/interactives/voter-guide/search-results/
https://www.lansingstatejournal.com/pages/interactives/11/2016/clinton-county-election-results/
https://www.lansingstatejournal.com/pages/interactives/11/2016/eaton-county-election-results/
https://www.lansingstatejournal.com/pages/interactives/11/2016/ingham-county-election-results/
https://www.lansingstatejournal.com/pages/interactives/2016-year-in-review-quiz/
https://www.lansingstatejournal.com/pages/interactives/2017-Clinton-County-election-results/
https://www.lansingstatejournal.com/pages/interactives/2017-Eaton-County-election-results/
https://www.lansingstatejournal.com/pages/interactives/2017-Ingham-County-election-results/
https://www.lansingstatejournal.com/pages/interactives/2018-primary-election-results-clinton-county/
https://www.lansingstatejournal.com/pages/interactives/2018-primary-election-results-eaton-county/
https://www.lansingstatejournal.com/pages/interactives/2018-primary-election-results-ingham-county/
https://www.lansingstatejournal.com/pages/interactives/360-Prep-Football-Stadiums/
https://www.lansingstatejournal.com/pages/interactives/action_page.php/
https://www.lansingstatejournal.com/pages/interactives/clinton-county-election/08/2016/
https://www.lansingstatejournal.com/pages/interactives/coronado-path-to-michigan-state-firebombing/
https://www.lansingstatejournal.com/pages/interactives/eastwood/
https://www.lansingstatejournal.com/pages/interactives/eaton-election-results/08/2016/
https://www.lansingstatejournal.com/pages/interactives/endangered-species-quiz/
https://www.lansingstatejournal.com/pages/interactives/flint-water-crisis-timeline/
https://www.lansingstatejournal.com/pages/interactives/flint-water-crisis/a-visual-essay/unheeded_warnings/
https://www.lansingstatejournal.com/pages/interactives/idaremeto/
https://www.lansingstatejournal.com/pages/interactives/ingham-election-results/08/02/2016/
https://www.lansingstatejournal.com/pages/interactives/lansing-beer-personality-quiz/
https://www.lansingstatejournal.com/pages/interactives/lansing-news-quiz-july/
https://www.lansingstatejournal.com/pages/interactives/lansing-news-quiz/
https://www.lansingstatejournal.com/pages/interactives/lansing-quiz/
https://www.lansingstatejournal.com/pages/interactives/larry-nassar-msu-connections-map/
https://www.lansingstatejournal.com/pages/interactives/map-christmas-tree-farms-michigan/
https://www.lansingstatejournal.com/pages/interactives/michigan-castles-tour/
https://www.lansingstatejournal.com/pages/interactives/michigan-musicians-quiz/
https://www.lansingstatejournal.com/pages/interactives/michigan-state-dantonio-izzo-quiz/
https://www.lansingstatejournal.com/pages/interactives/michigan-state-ncaa-history/
https://www.lansingstatejournal.com/pages/interactives/michigan-state-university-timeline/
https://www.lansingstatejournal.com/pages/interactives/november-election-results/
https://www.lansingstatejournal.com/pages/interactives/quiz-michigan-winters/
https://www.lansingstatejournal.com/pages/interactives/quiz/invasives/
https://www.lansingstatejournal.com/pages/interactives/shootings-zip-map/
https://www.lansingstatejournal.com/pages/interactives/sponsor-wharton-broadway-quiz/
https://www.lansingstatejournal.com/pages/interactives/star-wars-avatarss/
https://www.lansingstatejournal.com/pages/interactives/state-budget/
https://www.lansingstatejournal.com/pages/interactives/statewide-election-results/08/02/2016/
https://www.lansingstatejournal.com/pages/interactives/superhero-quiz/
https://www.lansingstatejournal.com/pages/interactives/tweetthis/
https://www.lansingstatejournal.com/pages/interactives/vacation-quiz/
https://www.ldnews.com/pages/interactives/ldn/specialsections/
https://www.livingstondaily.com/pages/interactives/11/2016/livingston-county-election-results/
https://www.livingstondaily.com/pages/interactives/2017-livingston-county-election-results/
https://www.livingstondaily.com/pages/interactives/2018-primary-election-results-livingston-county/
https://www.livingstondaily.com/pages/interactives/flint-water-crisis-timeline/
https://www.livingstondaily.com/pages/interactives/livingston-election-results/08/2016/
https://www.livingstondaily.com/pages/interactives/michigan-musicians-quiz/
https://www.livingstondaily.com/pages/interactives/quiz-michigan-winters/
https://www.livingstondaily.com/pages/interactives/quiz/invasives/
https://www.livingstondaily.com/pages/interactives/state-budget/
https://www.livingstondaily.com/pages/interactives/statewide-election-results/08/02/2016/
https://www.livingstondaily.com/pages/interactives/superhero-quiz/
https://www.mansfieldnewsjournal.com/pages/interactives/voter-guide/
https://www.mansfieldnewsjournal.com/pages/interactives/voter-guide/candidate-profile/
https://www.mansfieldnewsjournal.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.mansfieldnewsjournal.com/pages/interactives/voter-guide/candidates-login/
https://www.mansfieldnewsjournal.com/pages/interactives/voter-guide/candidates-preview/
https://www.mansfieldnewsjournal.com/pages/interactives/voter-guide/sample-ballot/
https://www.mansfieldnewsjournal.com/pages/interactives/voter-guide/search-results/
https://www.marionstar.com/pages/interactives/voter-guide/
https://www.marionstar.com/pages/interactives/voter-guide/candidate-profile/
https://www.marionstar.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.marionstar.com/pages/interactives/voter-guide/candidates-login/
https://www.marionstar.com/pages/interactives/voter-guide/candidates-preview/
https://www.marionstar.com/pages/interactives/voter-guide/sample-ballot/
https://www.marionstar.com/pages/interactives/voter-guide/search-results/
https://www.marshfieldnewsherald.com/pages/interactives/preps-plus-scoreboard/
https://www.naplesnews.com/pages/interactives/archives/
https://www.naplesnews.com/pages/interactives/columnists/
https://www.naplesnews.com/pages/interactives/comics/
https://www.naplesnews.com/pages/interactives/legal-notices/
https://www.naplesnews.com/pages/interactives/puzzles/
https://www.naplesnews.com/pages/interactives/scanner/
https://www.newarkadvocate.com/pages/interactives/voter-guide/
https://www.newarkadvocate.com/pages/interactives/voter-guide/candidate-profile/
https://www.newarkadvocate.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.newarkadvocate.com/pages/interactives/voter-guide/candidates-login/
https://www.newarkadvocate.com/pages/interactives/voter-guide/candidates-preview/
https://www.newarkadvocate.com/pages/interactives/voter-guide/sample-ballot/
https://www.newarkadvocate.com/pages/interactives/voter-guide/search-results/
https://www.news-leader.com/pages/interactives/games/
https://www.newsleader.com/pages/interactives/prey/
https://www.northjersey.com/pages/interactives/events/
https://www.northjersey.com/pages/interactives/whos-my-rep/
https://www.pnj.com/pages/interactives/civiccon/
https://www.portclintonnewsherald.com/pages/interactives/voter-guide/
https://www.portclintonnewsherald.com/pages/interactives/voter-guide/candidate-profile/
https://www.portclintonnewsherald.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.portclintonnewsherald.com/pages/interactives/voter-guide/candidates-login/
https://www.portclintonnewsherald.com/pages/interactives/voter-guide/candidates-preview/
https://www.portclintonnewsherald.com/pages/interactives/voter-guide/sample-ballot/
https://www.portclintonnewsherald.com/pages/interactives/voter-guide/search-results/
https://www.postcrescent.com/pages/interactives/preps-plus-scoreboard/
https://www.press-citizen.com/pages/interactives/iowa-state-fair-political-soapbox/
https://www.publicopiniononline.com/pages/interactives/chambersburg/specialsections/
https://www.redding.com/pages/interactives/2015-crime-stats/
https://www.redding.com/pages/interactives/2016-candidate-contributions/
https://www.redding.com/pages/interactives/2016-redding-contributions/
https://www.redding.com/pages/interactives/accident-locations/
https://www.redding.com/pages/interactives/best-of-the-west/
https://www.redding.com/pages/interactives/bestofdeals-form/
https://www.redding.com/pages/interactives/bestofdeals-merchant-form/
https://www.redding.com/pages/interactives/candidate-contributions/
https://www.redding.com/pages/interactives/circulars/
https://www.redding.com/pages/interactives/company-spotlight/
https://www.redding.com/pages/interactives/databases/
https://www.redding.com/pages/interactives/forms/
https://www.redding.com/pages/interactives/help-old/
https://www.redding.com/pages/interactives/heroin/
https://www.redding.com/pages/interactives/hospital-data/
https://www.redding.com/pages/interactives/hotel-calls/
https://www.redding.com/pages/interactives/opioids2017/
https://www.redding.com/pages/interactives/police-calls/
https://www.redding.com/pages/interactives/police-scanner/
https://www.redding.com/pages/interactives/public-salaries/
https://www.redding.com/pages/interactives/reu-bill-calculator/
https://www.redding.com/pages/interactives/shasta-county-claims/
https://www.redding.com/pages/interactives/submit-announcement/
https://www.redding.com/pages/interactives/submit-letter/
https://www.redding.com/pages/interactives/submit-newstip/
https://www.redding.com/pages/interactives/submit-obituary/
https://www.redding.com/pages/interactives/submit-press-release/
https://www.redding.com/pages/interactives/submit-sponsorship/
https://www.redding.com/pages/interactives/subscribe/
https://www.redding.com/pages/interactives/tests/justice-landing/
https://www.redding.com/pages/interactives/unsolved-murders-redding/
https://www.redding.com/pages/interactives/water-audit/
https://www.redding.com/pages/interactives/water-rationing/
https://www.redding.com/pages/interactives/webmaster-form/
https://www.reporternews.com/pages/interactives/abilene-regional-airport-readings/
https://www.reporternews.com/pages/interactives/abilene-rocks/
https://www.reporternews.com/pages/interactives/circulars/
https://www.reporternews.com/pages/interactives/crossword/
https://www.reporternews.com/pages/interactives/game-night-live/
https://www.reporternews.com/pages/interactives/gas-prices/
https://www.reporternews.com/pages/interactives/go-friday-night-scoreboard/
https://www.reporternews.com/pages/interactives/hourly-forecast/
https://www.reporternews.com/pages/interactives/lake-levels/
https://www.reporternews.com/pages/interactives/live-air-traffic/
https://www.reporternews.com/pages/interactives/nws-abilene-forecast/
https://www.reporternews.com/pages/interactives/radar-model/
https://www.reporternews.com/pages/interactives/submit-anniversary/
https://www.reporternews.com/pages/interactives/submit-engagement/
https://www.reporternews.com/pages/interactives/submit-wedding/
https://www.reporternews.com/pages/interactives/sudoku/
https://www.reporternews.com/pages/interactives/tv-listings/
https://www.reporternews.com/pages/interactives/weather-records/
https://www.rgj.com/pages/interactives/best-of-the-west/
https://www.rgj.com/pages/interactives/ski-dev-26/
https://www.sheboyganpress.com/pages/interactives/preps-plus-scoreboard/
https://www.statesmanjournal.com/pages/interactives/best-of-the-west/
https://www.statesmanjournal.com/pages/interactives/ceros-homelessness-test/
https://www.stevenspointjournal.com/pages/interactives/preps-plus-scoreboard/
https://www.tcpalm.com/pages/interactives/circulars/
https://www.tcpalm.com/pages/interactives/crime-database/
https://www.tcpalm.com/pages/interactives/crossword-puzzle/
https://www.tcpalm.com/pages/interactives/database/hurricanes/
https://www.tcpalm.com/pages/interactives/database/UniformCrimeReports/
https://www.tcpalm.com/pages/interactives/events-calendar/
https://www.tcpalm.com/pages/interactives/forms/
https://www.tcpalm.com/pages/interactives/gas-prices/
https://www.tcpalm.com/pages/interactives/holiday-bazaars/
https://www.tcpalm.com/pages/interactives/life-before-death/
https://www.tcpalm.com/pages/interactives/newspapers-in-education/
https://www.tcpalm.com/pages/interactives/noaa-database/
https://www.tcpalm.com/pages/interactives/restaurant-inspections/
https://www.tcpalm.com/pages/interactives/scanner/
https://www.tcpalm.com/pages/interactives/sudoku-puzzle/
https://www.tcpalm.com/pages/interactives/summer-camps-database/
https://www.tcpalm.com/pages/interactives/we-sponsor-the-treasure-coast/
https://www.thecalifornian.com/pages/interactives/tests/justice-landing/
https://www.thegleaner.com/pages/interactives/marketplace-deals/
https://www.thenews-messenger.com/pages/interactives/voter-guide/
https://www.thenews-messenger.com/pages/interactives/voter-guide/candidate-profile/
https://www.thenews-messenger.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.thenews-messenger.com/pages/interactives/voter-guide/candidates-login/
https://www.thenews-messenger.com/pages/interactives/voter-guide/candidates-preview/
https://www.thenews-messenger.com/pages/interactives/voter-guide/sample-ballot/
https://www.thenews-messenger.com/pages/interactives/voter-guide/search-results/
https://www.thenorthwestern.com/pages/interactives/preps-plus-scoreboard/
https://www.thespectrum.com/pages/interactives/best-of-the-west/
https://www.thetimesherald.com/pages/interactives/flint-water-crisis-timeline/
https://www.thetimesherald.com/pages/interactives/quiz-michigan-winters/
https://www.thetimesherald.com/pages/interactives/state-budget/
https://www.thetimesherald.com/pages/interactives/statewide-election-results/08/02/2016/
https://www.thetimesherald.com/pages/interactives/superhero-quiz/
https://www.timesrecordnews.com/pages/interactives/circulars/
https://www.timesrecordnews.com/pages/interactives/crossword/
https://www.timesrecordnews.com/pages/interactives/help/
https://www.timesrecordnews.com/pages/interactives/police-scanner/
https://www.timesrecordnews.com/pages/interactives/puzzles/
https://www.timesrecordnews.com/pages/interactives/state-high-school-standings/
https://www.timesrecordnews.com/pages/interactives/submit-anniversary/
https://www.timesrecordnews.com/pages/interactives/submit-engagement/
https://www.timesrecordnews.com/pages/interactives/submit-letter/
https://www.timesrecordnews.com/pages/interactives/submit-wedding/
https://www.timesrecordnews.com/pages/interactives/weather-cam/
https://www.vcstar.com/pages/interactives/bell-ringer-2016/
https://www.vcstar.com/pages/interactives/best-of-the-west/
https://www.vcstar.com/pages/interactives/circulars/
https://www.vcstar.com/pages/interactives/gas-prices/
https://www.vcstar.com/pages/interactives/OLD-puzzles/
https://www.vcstar.com/pages/interactives/puzzles/
https://www.vcstar.com/pages/interactives/special-sections/
https://www.vcstar.com/pages/interactives/sponsorship-ad/
https://www.vcstar.com/pages/interactives/sponsorship-request/
https://www.vcstar.com/pages/interactives/tests/justice-landing/
https://www.vcstar.com/pages/interactives/vin-scully/
https://www.visaliatimesdelta.com/pages/interactives/tests/justice-landing/
https://www.wausaudailyherald.com/pages/interactives/preps-plus-scoreboard/
https://www.wisconsinrapidstribune.com/pages/interactives/preps-plus-scoreboard/
https://www.wisfarmer.com/pages/interactives/commodities/
https://www.ydr.com/pages/interactives/homesinyork2/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/candidate-profile/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/candidates-confirmation/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/candidates-login/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/candidates-preview/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/sample-ballot/
https://www.zanesvilletimesrecorder.com/pages/interactives/voter-guide/search-results/
`
const urlsStringThree = `
https://www.usatoday.com/pages/interactives/082016-osiris-graphic/
https://www.usatoday.com/pages/interactives/100000-lives-lost-honoring-coronavirus-victims/
https://www.usatoday.com/pages/interactives/1619-african-slavery-history-maps-routes-interactive-graphic/
https://www.usatoday.com/pages/interactives/2015-music-festivals/
https://www.usatoday.com/pages/interactives/2015-ski-championships/
https://www.usatoday.com/pages/interactives/2016-superpac-donors/
https://www.usatoday.com/pages/interactives/2016-trump-flipped-counties/
https://www.usatoday.com/pages/interactives/2016-year-in-photos/
https://www.usatoday.com/pages/interactives/2016/election/poll-tracker/
https://www.usatoday.com/pages/interactives/2016/fall-music-preview/
https://www.usatoday.com/pages/interactives/2016/state-ads/
https://www.usatoday.com/pages/interactives/2017-triple-crown/
https://www.usatoday.com/pages/interactives/2017-year-in-photos/
https://www.usatoday.com/pages/interactives/2019-year-in-photos/
https://www.usatoday.com/pages/interactives/a-peoples-journey/
https://www.usatoday.com/pages/interactives/agua-caliente-checkerboard-land-leasing/
https://www.usatoday.com/pages/interactives/anthem-full-service-creative-solutions/
https://www.usatoday.com/pages/interactives/asbestos-sharia-law-model-bills-lobbyists-special-interests-influence-state-laws/
https://www.usatoday.com/pages/interactives/author_chat/
https://www.usatoday.com/pages/interactives/baltimore-unrest-video/
https://www.usatoday.com/pages/interactives/behind-the-shots/
https://www.usatoday.com/pages/interactives/biolabs/
https://www.usatoday.com/pages/interactives/blacklivesmatter-map/
https://www.usatoday.com/pages/interactives/blacks-killed-police-chases-higher-rate/
https://www.usatoday.com/pages/interactives/bolt-simulator/
https://www.usatoday.com/pages/interactives/broadway-guide/
https://www.usatoday.com/pages/interactives/brussels-victims/
https://www.usatoday.com/pages/interactives/california-dam-inspections/
https://www.usatoday.com/pages/interactives/california-power-grid-expansion/
https://www.usatoday.com/pages/interactives/campaign-coloring-book/
https://www.usatoday.com/pages/interactives/campaign-slogan-generator/
https://www.usatoday.com/pages/interactives/candidate-match-game/
https://www.usatoday.com/pages/interactives/candidate-nickname-quiz/
https://www.usatoday.com/pages/interactives/chernobyl/
https://www.usatoday.com/pages/interactives/clinton-nation/
https://www.usatoday.com/pages/interactives/college-2016-election/
https://www.usatoday.com/pages/interactives/colleges-out-of-state-enrollment-database/
https://www.usatoday.com/pages/interactives/costliest-hurricanes-united-states/
https://www.usatoday.com/pages/interactives/critical-va-vacancies/
https://www.usatoday.com/pages/interactives/cuba360-spanish/
https://www.usatoday.com/pages/interactives/cuba360/
https://www.usatoday.com/pages/interactives/day-of-infamy/
https://www.usatoday.com/pages/interactives/desertsun/2016/11/08/election-results/
https://www.usatoday.com/pages/interactives/div100-map/
https://www.usatoday.com/pages/interactives/diverse-map/
https://www.usatoday.com/pages/interactives/diversity-map/
https://www.usatoday.com/pages/interactives/eclipse-2017/
https://www.usatoday.com/pages/interactives/elections-forecast-2014-133/
https://www.usatoday.com/pages/interactives/elections-forecast-2014-a75/
https://www.usatoday.com/pages/interactives/elections-forecast-2014/
https://www.usatoday.com/pages/interactives/elections-results-2014-stage/
https://www.usatoday.com/pages/interactives/elections-results-2014/
https://www.usatoday.com/pages/interactives/elections-results-primaries-2016-stage/
https://www.usatoday.com/pages/interactives/elections-results-primaries-2016/
https://www.usatoday.com/pages/interactives/elections/the-deciders/
https://www.usatoday.com/pages/interactives/elections/trump-support/
https://www.usatoday.com/pages/interactives/electoral-college-2016/
https://www.usatoday.com/pages/interactives/embark-travel-survey/
https://www.usatoday.com/pages/interactives/emoji-match-game/
https://www.usatoday.com/pages/interactives/eventful-mobile/
https://www.usatoday.com/pages/interactives/faces-of-lgbtq-pride-month-2018/
https://www.usatoday.com/pages/interactives/faces-of-pride-2018/
https://www.usatoday.com/pages/interactives/faces-of-pride/
https://www.usatoday.com/pages/interactives/fb-barometer/
https://www.usatoday.com/pages/interactives/fb-share/
https://www.usatoday.com/pages/interactives/finding-home-journey-of-syrian-refugee/
https://www.usatoday.com/pages/interactives/finding-home-journey-of-syrian-refugees-brightcove/
https://www.usatoday.com/pages/interactives/finding-home-journey-of-syrian-refugees/
https://www.usatoday.com/pages/interactives/gas-pipeline-incidents-map/
https://www.usatoday.com/pages/interactives/GET-Creative-01/
https://www.usatoday.com/pages/interactives/getcreative/belated-holiday-card/
https://www.usatoday.com/pages/interactives/gleecember/
https://www.usatoday.com/pages/interactives/gone/
https://www.usatoday.com/pages/interactives/graphics/afghanistan-in-memoriam/
https://www.usatoday.com/pages/interactives/graphics/deportation-explainer/
https://www.usatoday.com/pages/interactives/graphics/let-it-snow-break-from-2020/
https://www.usatoday.com/pages/interactives/graphics/nasa-mars-mission-landing-2021-perseverance-rover/
https://www.usatoday.com/pages/interactives/graphics/nasa-mars-mission-perserverance-atlas-rocket/
https://www.usatoday.com/pages/interactives/graphics/statue-of-liberty-birthday/
https://www.usatoday.com/pages/interactives/groundwater/
https://www.usatoday.com/pages/interactives/guam-clergy-sex-abuse-lawsuits/
https://www.usatoday.com/pages/interactives/handmaids-tale-and-womens-rights-discussion/
https://www.usatoday.com/pages/interactives/harvest-of-change/
https://www.usatoday.com/pages/interactives/high-speed-chases/
https://www.usatoday.com/pages/interactives/hopwood-timeline/
https://www.usatoday.com/pages/interactives/how-the-election-unfolded/
https://www.usatoday.com/pages/interactives/hurricane-tracker/
https://www.usatoday.com/pages/interactives/idaremeto/
https://www.usatoday.com/pages/interactives/intheirwords-obama/
https://www.usatoday.com/pages/interactives/InTheirWords-same-sex-marriage/
https://www.usatoday.com/pages/interactives/intheirwords-transgender/
https://www.usatoday.com/pages/interactives/InTheirWords-women/
https://www.usatoday.com/pages/interactives/InTheirWords/
https://www.usatoday.com/pages/interactives/ipad-charts/
https://www.usatoday.com/pages/interactives/isil-arrests-map/
https://www.usatoday.com/pages/interactives/isis-bride-timeline/
https://www.usatoday.com/pages/interactives/kanye-west-confidence-generator/
https://www.usatoday.com/pages/interactives/la-floods-august-2016/
https://www.usatoday.com/pages/interactives/Land--Space-Development-Database/
https://www.usatoday.com/pages/interactives/larry-nassar-timeline/
https://www.usatoday.com/pages/interactives/larsen-c-ice-shelf-antarctic/
https://www.usatoday.com/pages/interactives/lead-water/
https://www.usatoday.com/pages/interactives/learn-more-about-your-va-hospital/
https://www.usatoday.com/pages/interactives/letterman-celebrity-guests-remember/
https://www.usatoday.com/pages/interactives/life/cast-your-vote-red-carpet-fashion-in-real-time/
https://www.usatoday.com/pages/interactives/life/fallout-from-weinstein/
https://www.usatoday.com/pages/interactives/life/save-our-shows-2018/
https://www.usatoday.com/pages/interactives/life/save-our-shows-2019/
https://www.usatoday.com/pages/interactives/life/save-our-shows-2020/
https://www.usatoday.com/pages/interactives/life/the-best-oscar-dresses-throughout-history/
https://www.usatoday.com/pages/interactives/life/the-harvey-weinstein-effect/
https://www.usatoday.com/pages/interactives/life/vertical-gallery/
https://www.usatoday.com/pages/interactives/metoo-anniversary-hollywood-whats-changed/
https://www.usatoday.com/pages/interactives/movie-roundup/
https://www.usatoday.com/pages/interactives/new-planet-discovered-08-2016/
https://www.usatoday.com/pages/interactives/news-quiz/
https://www.usatoday.com/pages/interactives/news/1968-the-year-that-transformed-the-nation/
https://www.usatoday.com/pages/interactives/news/1986-the-year-that-transformed-the-nation/
https://www.usatoday.com/pages/interactives/news/2017-year-in-review-50-stories-50-states/
https://www.usatoday.com/pages/interactives/news/2018/05/russian-facebook-ads/
https://www.usatoday.com/pages/interactives/news/2018/supereme-court-top-decisions/
https://www.usatoday.com/pages/interactives/news/2019/supreme-court-decisions/
https://www.usatoday.com/pages/interactives/news/2020-election-florida-voters-inactive/
https://www.usatoday.com/pages/interactives/news/broward-county-victims/
https://www.usatoday.com/pages/interactives/news/california-wildfires-carr-fire-data/
https://www.usatoday.com/pages/interactives/news/coronavirus-covid-19-china-transmission-how-it-spread/
https://www.usatoday.com/pages/interactives/news/coronavirus-covid-19-defense-proper-hand-washing/
https://www.usatoday.com/pages/interactives/news/coronavirus-covid-spread-quickly-how-to-slow-it-down/
https://www.usatoday.com/pages/interactives/news/executive-orders/
https://www.usatoday.com/pages/interactives/news/graphics/coronavirus-death-pork-plants-meat-packing-visual-explainer/
https://www.usatoday.com/pages/interactives/news/graphics/march-2020-tornado-path-nashville-cookeville-putnam-tennessee/
https://www.usatoday.com/pages/interactives/news/graphics/spin-cycle-how-cdc-failed-local-officials-covid-19/
https://www.usatoday.com/pages/interactives/news/graphics/supreme-court-decisions-2020-2021/
https://www.usatoday.com/pages/interactives/news/gun-control-mass-killings-timeline/
https://www.usatoday.com/pages/interactives/news/harvery-weinstein-timeline/
https://www.usatoday.com/pages/interactives/news/impeachment-who-is-who-cast-of-characters/
https://www.usatoday.com/pages/interactives/news/investigations/year-of-violence-G4S-dangerous-security-guards/
https://www.usatoday.com/pages/interactives/news/las-vegas-victims/
https://www.usatoday.com/pages/interactives/news/new-race-moon-apollo/
https://www.usatoday.com/pages/interactives/news/politics/trump-off-message-timeline/
https://www.usatoday.com/pages/interactives/news/retail-giants-enable-trucker-exploitation/
https://www.usatoday.com/pages/interactives/news/reverse-mortgage-national-foreclosure-rate-map/
https://www.usatoday.com/pages/interactives/news/rigged-asleep-at-the-wheel/
https://www.usatoday.com/pages/interactives/news/rigged-forced-into-debt-worked-past-exhaustion-left-with-nothing-es/
https://www.usatoday.com/pages/interactives/news/rigged-forced-into-debt-worked-past-exhaustion-left-with-nothing/
https://www.usatoday.com/pages/interactives/news/rigged-retail-giants-enable-trucker-exploitation/
https://www.usatoday.com/pages/interactives/news/rigged-shell-games-how-trucking-companies-that-cheat-drivers-dodge-penalties/
https://www.usatoday.com/pages/interactives/news/shayrat-airfield-airstike/
https://www.usatoday.com/pages/interactives/news/spelling-bee-interactive-quiz/
https://www.usatoday.com/pages/interactives/news/supreme-court-decisions-2019-2020/
https://www.usatoday.com/pages/interactives/news/the-trump-years/
https://www.usatoday.com/pages/interactives/news/trump-impeachment-2-2021-how-the-senate-voted/
https://www.usatoday.com/pages/interactives/news/trump-impeachment-articles-how-the-senate-voted/
https://www.usatoday.com/pages/interactives/news/trump-impeachment-how-the-senate-voted/
https://www.usatoday.com/pages/interactives/news/trump-putin-timeline/
https://www.usatoday.com/pages/interactives/news/wikileaks-cia-hacks/
https://www.usatoday.com/pages/interactives/news/world/european-terror-attacks/
https://www.usatoday.com/pages/interactives/online-discussion-mass-shootings-slows-fast/
https://www.usatoday.com/pages/interactives/opinion/reentry-photo-audio-essay/
https://www.usatoday.com/pages/interactives/orlando-victims-anniversary/
https://www.usatoday.com/pages/interactives/orlando-victims/
https://www.usatoday.com/pages/interactives/oscars-ultimate-closet/
https://www.usatoday.com/pages/interactives/paris-victims/
https://www.usatoday.com/pages/interactives/pearl-harbor-anniversary-timeline/
https://www.usatoday.com/pages/interactives/pearl-harbor-wwii-wreckage-dive/
https://www.usatoday.com/pages/interactives/photos/as-real-as-it-gets/
https://www.usatoday.com/pages/interactives/pictures-of-2018/
https://www.usatoday.com/pages/interactives/podcast-player/
https://www.usatoday.com/pages/interactives/police-chases/
https://www.usatoday.com/pages/interactives/police-killings-map/
https://www.usatoday.com/pages/interactives/policedata/search/
https://www.usatoday.com/pages/interactives/political-emoji/
https://www.usatoday.com/pages/interactives/poll-tracker-2016/
https://www.usatoday.com/pages/interactives/prop-47-california-prison-reform/
https://www.usatoday.com/pages/interactives/psychology-of-infertility-surrogacy-ivf-adoption/
https://www.usatoday.com/pages/interactives/quiz-v2/
https://www.usatoday.com/pages/interactives/quiz/
https://www.usatoday.com/pages/interactives/quizzes/new-years/
https://www.usatoday.com/pages/interactives/quizzette-demo/
https://www.usatoday.com/pages/interactives/race-together/
https://www.usatoday.com/pages/interactives/reaching-new-heights/
https://www.usatoday.com/pages/interactives/record-day-2015/
https://www.usatoday.com/pages/interactives/refugees/
https://www.usatoday.com/pages/interactives/require/
https://www.usatoday.com/pages/interactives/salton-sea/
https://www.usatoday.com/pages/interactives/salton-sea/as-the-salton-sea-deteriorates-bird-populations-are-crashing/
https://www.usatoday.com/pages/interactives/salton-sea/california-far-from-solutions-as-salton-sea-crisis-looms/
https://www.usatoday.com/pages/interactives/salton-sea/the-dying-salton-sea/
https://www.usatoday.com/pages/interactives/salton-sea/timeline/
https://www.usatoday.com/pages/interactives/salton-sea/toxic-dust-and-asthma-plague-salton-sea-communities/
https://www.usatoday.com/pages/interactives/salton-sea/two-paths-for-long-term-fixes-at-californias-shrinking-sea/
https://www.usatoday.com/pages/interactives/save-our-shows-2017/
https://www.usatoday.com/pages/interactives/science-of-opioids/
https://www.usatoday.com/pages/interactives/scotus-tracker-2015/
https://www.usatoday.com/pages/interactives/scotus-tracker/
https://www.usatoday.com/pages/interactives/sea-level-change-graphic/
https://www.usatoday.com/pages/interactives/seven-days-of-heroin-epidemic-cincinnati/
https://www.usatoday.com/pages/interactives/social-player/
https://www.usatoday.com/pages/interactives/solar-eclipse-2017/
https://www.usatoday.com/pages/interactives/sos-2015/
https://www.usatoday.com/pages/interactives/sos-2016/
https://www.usatoday.com/pages/interactives/spacex-launch-graphic/
https://www.usatoday.com/pages/interactives/spelling-bee/
https://www.usatoday.com/pages/interactives/spirit-of-st-louis-anniversary/
https://www.usatoday.com/pages/interactives/sponsor-quiz/
https://www.usatoday.com/pages/interactives/sports/winter-olympics-2018-team-usa/
https://www.usatoday.com/pages/interactives/spring-cleaning/
https://www.usatoday.com/pages/interactives/star-wars-avatars/
https://www.usatoday.com/pages/interactives/statehouses/2015-la-1131-sb172/
https://www.usatoday.com/pages/interactives/states-lead-enforcement-letters/
https://www.usatoday.com/pages/interactives/storm-tracker/
https://www.usatoday.com/pages/interactives/story-from/National-Grid/Cleaner-More-Efficient-Future-01/
https://www.usatoday.com/pages/interactives/streaming-music-services/
https://www.usatoday.com/pages/interactives/streaming-video-services/
https://www.usatoday.com/pages/interactives/sunday-standings/
https://www.usatoday.com/pages/interactives/suspicious-russian-deaths-sacrificial-pawns-or-coincidence/
https://www.usatoday.com/pages/interactives/teacher-journey/
https://www.usatoday.com/pages/interactives/thanks-obama/
https://www.usatoday.com/pages/interactives/the-sex-talk-the-conversation-that-isnt-happening-about-sexual-assault/
https://www.usatoday.com/pages/interactives/top-college-stories/
https://www.usatoday.com/pages/interactives/trump-100-days/
https://www.usatoday.com/pages/interactives/trump-and-the-law/
https://www.usatoday.com/pages/interactives/trump-cabinet/
https://www.usatoday.com/pages/interactives/trump-lawsuits/
https://www.usatoday.com/pages/interactives/trump-nation/
https://www.usatoday.com/pages/interactives/trumps-10-foreign-deals-with-close-to-power/
https://www.usatoday.com/pages/interactives/tsa-claims/
https://www.usatoday.com/pages/interactives/untested-rape-kits/
https://www.usatoday.com/pages/interactives/va-vacancies/
https://www.usatoday.com/pages/interactives/vanishingpollingplaces/
https://www.usatoday.com/pages/interactives/whats-working-survery-response/
https://www.usatoday.com/pages/interactives/whatsworking/
https://www.usatoday.com/pages/interactives/wilmington-gun-investigation-chain-of-violence/
https://www.usatoday.com/pages/interactives/women-suffrage-timeline/
https://www.usatoday.com/pages/interactives/womens-march-photos/
https://www.usatoday.com/pages/interactives/your-take/
https://www.usatoday.com/pages/interactives/zika-graphic/
`
const urlsTest = `
https://www.usatoday.com/pages/interactives/storm-tracker/
https://www.usatoday.com/pages/interactives/graphics/afghanistan-in-memoriam/
https://www.usatoday.com/pages/interactives/larry-nassar-timeline/
https://www.azcentral.com/pages/interactives/news/local/arizona-data/arizona-government-salary-database/
https://www.jsonline.com/pages/interactives/milwaukee-tv-listings/
https://www.knoxnews.com/pages/interactives/lowest-gas-prices-in-knoxville/
https://static.cincinnati.com/classifiedshelp/
https://static.tennessean.com/rss/
https://static.indystar.com/en/aboutus/
`

const urls = urlsString.replace(/https/g,",https").split(",");
const urlsTwo = urlsStringTwo.replace(/https/g,",https").split(",");
const urlsThree = urlsStringThree.replace(/https/g,",https").split(",");
const urlsFour = urlsTest.replace(/https/g,",https").split(",");

 

module.exports = {
  urls: urls,
  urlsTwo: urlsTwo,
  urlsThree: urlsThree,
  urlsFour: urlsFour
}
